GET  http://localhost:3000/ChocoAndino/users

###
POST http://localhost:3000/ChocoAndino/users/add
Content-Type: application/json

{
"user": "Diego",
"mail": "dapaez2@espe.edu.ec",
"password": "1234",
"dni": "1723564852",
"type": "user",
"active": true
}